export enum EColorPalette {
    ENGINEERINGORANGE = "#BA2D0B",
    MINTCREAM = "#F3F8F2",
    FRENCHGRAY = "#B8C2CB",
    JET = "#333138",
    JETHOVER = "#1F1E21",
    COOLGRAY = "#7D8CA3",
    BURNTSIENNA = "#EE6C4D"
}
